name: EnderPearlTeleporter
version: '1.1-SNAPSHOT'
main: io.github.xiyayizhang.enderPearlTeleporter.EnderPearlTeleporter
api-version: '1.21'
authors: [ xiayizhang ]
description: End eye teleportation.
website: https://xiayizhang.github.io
commands:
  binde:
    description: bind endpearl to a player
    usage: /binde <player>
    #permission: EnderPearlTeleporter.bind
    #permission-message: 你不能执行它.
  tpe:
    description: Teleport the player that he/she was bound to the Ender Pearl here
    usage: /tpe <player>
    #permission: EnderPearlTeleporter.tp
    #permission-message: 你不能执行它.